-- Daily Task Manager - Supabase schema
-- Run this first in Supabase Dashboard -> SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'employee' check (role in ('admin','employee')),
  department text,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamp without time zone not null default current_timestamp
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  status text not null default 'active' check (status in ('active','inactive'))
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.users(id) on delete cascade,
  task_date date not null,
  task_description text not null,
  category_id bigint references public.categories(id) on delete set null,
  priority text not null default 'Medium' check (priority in ('Low','Medium','High','Critical')),
  due_date text,
  status text not null default 'Not Started' check (status in ('Not Started','In Progress','Completed','Pending','Blocked','Cancelled')),
  remarks text,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp,
  client_name text,
  task_type text,
  poc text,
  content_responsible text,
  responsible_editor text,
  reference_links text,
  time_taken text,
  editor_remarks text,
  acc_manager_remark text,
  manager_remark text,
  sheet_day text,
  raw_status text,
  raw_priority text,
  source text not null default 'manual',
  source_sheet_key text,
  source_row bigint,
  synced_at timestamp without time zone
);

create table if not exists public.google_sheet_settings (
  id integer primary key check (id = 1),
  sheet_url text not null default '',
  sheet_id text not null default '',
  gid text not null default '0',
  sync_interval integer not null default 60,
  sync_year integer not null default extract(year from current_date)::integer,
  enabled integer not null default 0 check (enabled in (0,1)),
  last_sync_at text,
  last_sync_status text,
  last_sync_message text,
  last_sync_count integer not null default 0
);

insert into public.google_sheet_settings(id) values (1) on conflict (id) do nothing;

create index if not exists idx_tasks_employee on public.tasks(employee_id);
create index if not exists idx_tasks_date on public.tasks(task_date);
create index if not exists idx_tasks_status on public.tasks(status);
create index if not exists idx_tasks_due on public.tasks(due_date);
create index if not exists idx_tasks_category on public.tasks(category_id);
create index if not exists idx_tasks_source on public.tasks(source);
create index if not exists idx_tasks_sheet_key on public.tasks(source_sheet_key);

-- Vercel calls Supabase only with the server-side service-role key.
-- Browser clients receive no direct table access.
alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.tasks enable row level security;
alter table public.google_sheet_settings enable row level security;
revoke all on public.users from anon, authenticated;
revoke all on public.categories from anon, authenticated;
revoke all on public.tasks from anon, authenticated;
revoke all on public.google_sheet_settings from anon, authenticated;
grant all on public.users to service_role;
grant all on public.categories to service_role;
grant all on public.tasks to service_role;
grant all on public.google_sheet_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Atomic replacement of the Google Sheet snapshot, matching the old SQLite behavior.
create or replace function public.replace_google_sheet_tasks(p_tasks jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  delete from public.tasks where source = 'google_sheet';

  insert into public.tasks (
    employee_id, task_date, task_description, category_id, priority, due_date, status, remarks,
    client_name, task_type, poc, content_responsible, responsible_editor, reference_links, time_taken,
    editor_remarks, acc_manager_remark, manager_remark, sheet_day, raw_status, raw_priority,
    source, source_sheet_key, source_row, synced_at, updated_at
  )
  select
    (x->>'employee_id')::bigint,
    (x->>'task_date')::date,
    x->>'task_description',
    nullif(x->>'category_id','')::bigint,
    coalesce(nullif(x->>'priority',''),'Medium'),
    nullif(x->>'due_date',''),
    coalesce(nullif(x->>'status',''),'Not Started'),
    coalesce(x->>'remarks',''),
    coalesce(x->>'client_name',''),
    coalesce(x->>'task_type',''),
    coalesce(x->>'poc',''),
    coalesce(x->>'content_responsible',''),
    coalesce(x->>'responsible_editor',''),
    coalesce(x->>'reference_links',''),
    coalesce(x->>'time_taken',''),
    coalesce(x->>'editor_remarks',''),
    coalesce(x->>'acc_manager_remark',''),
    coalesce(x->>'manager_remark',''),
    coalesce(x->>'sheet_day',''),
    coalesce(x->>'raw_status',''),
    coalesce(x->>'raw_priority',''),
    'google_sheet',
    x->>'source_sheet_key',
    nullif(x->>'source_row','')::bigint,
    nullif(x->>'synced_at','')::timestamp,
    coalesce(nullif(x->>'updated_at','')::timestamp, current_timestamp)
  from jsonb_array_elements(coalesce(p_tasks,'[]'::jsonb)) as x;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.replace_google_sheet_tasks(jsonb) from public, anon, authenticated;
grant execute on function public.replace_google_sheet_tasks(jsonb) to service_role;
